Initial presice package structure
mojin-robotics/precise_ros pull request #1
Opened 2020-10-13 17:34 UTC by benmaidel

2020-10-13 18:37 UTC, fmessmer requested changes
thanks...I will continue based on this
I think we still need to support kinetic-devel fir the time being...

2020-10-14 06:11 UTC, floweisshardt commented on precise_driver/package.xml
> +  <license>private</license>
should be Apache 2

2020-10-14 06:11 UTC, floweisshardt commented on precise_description/package.xml
> +  <license>BSD</license>
should be Apache 2

2020-10-14 09:11 UTC, fmessmer commented
as discussed: I modified the default branch (and the target branch of this PR) to `kinetic-devel` - as the HW is still kinetic for the time being...but code should still support both distros

2020-10-14 11:27 UTC, closed without merging